apiVersion: controller.kubeslice.io/v1alpha1
kind: SliceConfig
metadata:
  name: convoy
spec:
  sliceSubnet: 10.1.0.0/16
  sliceType: Application
  sliceGatewayProvider:
    sliceGatewayType: OpenVPN
    sliceCaType: Local
  sliceIpamType: Local
  clusters:
    - WORKER
  qosProfileDetails:
    queueType: HTB
    priority: 1
    tcType: BANDWIDTH_CONTROL
    bandwidthCeilingKbps: 5120
    bandwidthGuaranteedKbps: 2560
    dscpClass: AF11
  namespaceIsolationProfile:
    applicationNamespaces:
     - namespace: iperf
       clusters:
       - '*'
     - namespace: bookinfo
       clusters:
       - '*'
    isolationEnabled: false                   #make this true in case you want to enable isolation
    allowedNamespaces:
     - namespace: kube-system
       clusters:
       - '*'
  # externalGatewayConfig:
  #   - ingress:
  #       enabled: false
  #     egress:
  #       enabled: true
  #     nsIngress:
  #       enabled: false
  #     gatewayType: istio
  #     clusters:
  #       - kind-worker-1
  #   - ingress:
  #       enabled: true
  #     egress:
  #       enabled: false 
  #     nsIngress:
  #       enabled: false
  #     gatewayType: istio 
  #     clusters:
  #       - kind-worker-2
